# -*- coding: utf-8 -*-
"""1st pr dl.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1efdZkcBp69EaU84K6ceSlVgG7egEOnph
"""

import numpy as np

import tensorflow as tf

print(tf.__version__)

from keras import datasets
# Load MNIST datasets from keras
(train_images, train_labels),(test_images, test_labels) = datasets.mnist.load_data()

train_images.shape

test_images.shape

!pip install Theano

import theano.tensor as T
from theano import function

pip install torch

import torch
import torch .nn as nn

print(torch.__version__)

torch.cuda.is_available()

